@rem Gradle wrapper launcher for QR Payment Queue (Windows).
@rem
@rem Lightweight launcher for gradle\wrapper\gradle-wrapper.jar.
@rem The canonical version is (re)generated by `gradle wrapper --gradle-version 8.11.1`.

@if "%DEBUG%"=="" @echo off
setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_HOME=%DIRNAME%
set WRAPPER_JAR=%APP_HOME%gradle\wrapper\gradle-wrapper.jar

if not exist "%WRAPPER_JAR%" (
    echo Gradle wrapper jar not found: %WRAPPER_JAR% 1>&2
    echo Run "gradle wrapper --gradle-version 8.11.1" once, or open the project in Android Studio. 1>&2
    exit /b 1
)

if defined JAVA_HOME (set JAVACMD=%JAVA_HOME%\bin\java.exe) else (set JAVACMD=java.exe)

"%JAVACMD%" -Xmx64m -Xms64m "-Dorg.gradle.appname=gradlew" -classpath "%WRAPPER_JAR%" org.gradle.wrapper.GradleWrapperMain %*

endlocal
