#!/bin/sh

# Gradle wrapper launcher for QR Payment Queue (POSIX).
#
# This is a lightweight launcher for gradle/wrapper/gradle-wrapper.jar.
# The canonical version is (re)generated by `gradle wrapper --gradle-version 8.11.1`,
# which the CI workflow runs before invoking ./gradlew.

set -e

APP_HOME=$(cd "$(dirname "$0")" && pwd -P)
APP_BASE_NAME=$(basename "$0")
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
    echo "Gradle wrapper jar not found: $WRAPPER_JAR" >&2
    echo "Run 'gradle wrapper --gradle-version 8.11.1' once, or open the project in Android Studio." >&2
    exit 1
fi

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

exec "$JAVACMD" -Xmx64m -Xms64m \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$WRAPPER_JAR" \
    org.gradle.wrapper.GradleWrapperMain "$@"
