package com.enjirad.qrqueue.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme — quiet neutrals with a deep teal accent.
val TealPrimaryLight = Color(0xFF0E5A50)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealPrimaryContainerLight = Color(0xFFD3EDE6)
val TealOnPrimaryContainerLight = Color(0xFF06332C)
val SageSecondaryLight = Color(0xFF4A635D)
val SageOnSecondaryLight = Color(0xFFFFFFFF)
val SageSecondaryContainerLight = Color(0xFFDCE7E3)
val SageOnSecondaryContainerLight = Color(0xFF203430)
val NeutralBackgroundLight = Color(0xFFF7F9F8)
val NeutralOnBackgroundLight = Color(0xFF191C1B)
val NeutralSurfaceLight = Color(0xFFFFFFFF)
val NeutralOnSurfaceLight = Color(0xFF191C1B)
val NeutralSurfaceVariantLight = Color(0xFFE3E9E6)
val NeutralOnSurfaceVariantLight = Color(0xFF4A544F)
val NeutralOutlineLight = Color(0xFF7B8580)
val NeutralOutlineVariantLight = Color(0xFFC9D2CE)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

// Dark scheme — same accent, dimmed surfaces.
val TealPrimaryDark = Color(0xFF8AD2C4)
val TealOnPrimaryDark = Color(0xFF003731)
val TealPrimaryContainerDark = Color(0xFF0B4A42)
val TealOnPrimaryContainerDark = Color(0xFFA6EFE0)
val SageSecondaryDark = Color(0xFFAFCCC5)
val SageOnSecondaryDark = Color(0xFF1B3531)
val SageSecondaryContainerDark = Color(0xFF324B46)
val SageOnSecondaryContainerDark = Color(0xFFCBE8E1)
val NeutralBackgroundDark = Color(0xFF0F1513)
val NeutralOnBackgroundDark = Color(0xFFDFE4E1)
val NeutralSurfaceDark = Color(0xFF161D1B)
val NeutralOnSurfaceDark = Color(0xFFDFE4E1)
val NeutralSurfaceVariantDark = Color(0xFF3F4946)
val NeutralOnSurfaceVariantDark = Color(0xFFBFC9C4)
val NeutralOutlineDark = Color(0xFF88938E)
val NeutralOutlineVariantDark = Color(0xFF3F4946)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
